# Generated by Django 6.0.5 on 2026-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedEDIFile",
            new_name="UploadedDocument",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="edi_file",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="document_mode",
            field=models.CharField(default="specific", max_length=50),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_histories",
                to="assistant.uploadeddocument",
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="model_type",
            field=models.CharField(default="gemini", max_length=50),
        ),
    ]
